                                                 Basic Numpy Exercises 
                                               Compiled by: Dr. Noman Islam

#### 1. Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions.

In [1]:
import numpy as np

In [2]:
myList = np.arange(-1.3, 2.5,0.06)

In [3]:
myList

array([-1.3 , -1.24, -1.18, -1.12, -1.06, -1.  , -0.94, -0.88, -0.82,
       -0.76, -0.7 , -0.64, -0.58, -0.52, -0.46, -0.4 , -0.34, -0.28,
       -0.22, -0.16, -0.1 , -0.04,  0.02,  0.08,  0.14,  0.2 ,  0.26,
        0.32,  0.38,  0.44,  0.5 ,  0.56,  0.62,  0.68,  0.74,  0.8 ,
        0.86,  0.92,  0.98,  1.04,  1.1 ,  1.16,  1.22,  1.28,  1.34,
        1.4 ,  1.46,  1.52,  1.58,  1.64,  1.7 ,  1.76,  1.82,  1.88,
        1.94,  2.  ,  2.06,  2.12,  2.18,  2.24,  2.3 ,  2.36,  2.42,
        2.48])

In [4]:
len(myList)

64

#### 2. Generate an array of length  3n  filled with the cyclic pattern 1, 2, 3.

In [5]:
myArray = np.full([5,3],[1,2,3])

In [6]:
myArray

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

#### 3. Create an array of the first 10 odd integers.

In [7]:
integerArray = np.arange(10)
oddArray = np.where(integerArray%2==1)
oddArray

(array([1, 3, 5, 7, 9]),)

#### 4. Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [8]:
zeroArray = np.zeros([10,10])
zeroArray[:,0] = 1
zeroArray[0,:] = 1
zeroArray[-1:,:] = 1
zeroArray[:,-1] = 1
zeroArray

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 5. Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [9]:
myArray = np.zeros([8,8])
myArray[1::2,::2] = 1
myArray[::2,1::2] = 1
myArray

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])